apiVersion: v1
kind: ConfigMap
metadata:
  name: video-ingest-config
  namespace: video-ingest-ns
data:
  AWS_REGION: "us-west-2"
  S3_BUCKET_NAME: "${S3_BUCKET_NAME}"     # Será substituído pelo CI/CD
  DYNAMO_TABLE_NAME: "${DYNAMO_TABLE_NAME}" # Será substituído pelo CI/CD
  SQS_QUEUE_URL: "${SQS_QUEUE_URL}"       # Será substituído pelo CI/CD