apiVersion: v1
kind: ConfigMap
metadata:
  name: video-ingest-config
data:
  AWS_REGION: "us-west-2"
  S3_BUCKET_NAME: "${S3_BUCKET_NAME}"
  DYNAMO_TABLE_NAME: "${DYNAMO_TABLE_NAME}"
  SQS_QUEUE_URL: "${SQS_QUEUE_URL}"