apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: video-ingest-ns
type: Opaque
stringData:
  # Estes valores s√£o gerenciados externamente pelo CI/CD
  aws_access_key_id: "placeholder"
  aws_secret_access_key: "placeholder"
  aws_session_token: "placeholder"