apiVersion: v1
kind: Service
metadata:
  name: video-ingest-svc
  namespace: video-ingest-ns
spec:
  type: LoadBalancer
  selector:
    app: video-ingest
  ports:
    - protocol: TCP
      port: 80      # Porta exposta para a internet
      targetPort: 8000 # Porta do container (FastAPI)