apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: video-ingest-ns

bases:
  - ../../base

patchesStrategicMerge:
  - patch-replicas.yaml

# Define prefixo para recursos se desejar (opcional)
# namePrefix: dev-

commonLabels:
  environment: dev