apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: video-ingest-ns

resources:
  - ../../base

patches:
  - path: patch-replicas.yml

labels:
  - pairs:
      environment: dev